INCLUDES += -I$(PKGDIRBASE)/monocypher/src
INCLUDES += -I$(PKGDIRBASE)/monocypher/src/optional
CFLAGS += -DED25519_SHA512
ifneq (,$(filter monocypher_sha512,$(USEMODULE)))
  DIRS += $(PKGDIRBASE)/monocypher/src/optional
endif

