
MODULE := mbedtls
SRC += asn1write.c
SRC += asn1parse.c
SRC += base64.c
SRC += bignum.c
SRC += dhm.c
#SRC += ecdh.c
SRC += ecdsa.c
SRC += ecp.c
SRC += ecp_curves.c
SRC += entropy.c
SRC += entropy_poll.c
SRC += error.c
SRC += hmac_drbg.c
SRC += md.c
#SRC += md5.c
SRC += md_wrap.c
SRC += oid.c
SRC += platform.c
#SRC += ripemd160.c
SRC += sha256.c
#SRC += sha1.c
#SRC += sha512.c
SRC += version.c
SRC += version_features.c
include $(RIOTBASE)/Makefile.base
