# for this board, we are using Segger's RTT as default terminal interface
USEMODULE += stdio_rtt
TERMPROG = $(RIOTTOOLS)/jlink/jlink.sh
TERMFLAGS = term-rtt

ifeq (pyocd,$(PROGRAMMER))
  # The board is not recognized automatically by pyocd, so the CPU target
  # option is passed explicitly
  export FLASH_TARGET_TYPE ?= -t $(CPU)
  include $(RIOTMAKE)/tools/pyocd.inc.mk
endif

# use shared Makefile.include
include $(RIOTBOARD)/common/nrf52xxxdk/Makefile.include
