INCLUDES += -I$(PKGDIRBASE)/tinycbor/src

ifneq (,$(filter tinycbor_float,$(USEMODULE)))
  CFLAGS +=
else
  CFLAGS += -DCBOR_NO_FLOATING_POINT
endif

# Declare pseudomodules here to be selfcontained
PSEUDOMODULES += tinycbor_float
